"""Type stubs for the compiled extension."""

from typing import Any, Literal, Sequence, overload

__version__: str

class HolosError(Exception): ...
class SyntaxError(HolosError): ...
class PolicyError(HolosError): ...

class Principal:
    def __init__(
        self,
        id: str | None = None,
        *,
        roles: Sequence[str] | None = None,
        clearance: int | None = None,
    ) -> None: ...
    @staticmethod
    def anonymous() -> Principal: ...

class Policy:
    def __init__(self) -> None: ...
    @staticmethod
    def deny_all() -> Policy: ...
    def allow_graph(self, iri: str) -> Policy: ...
    def allow_predicate(self, iri: str) -> Policy: ...
    def deny_predicate(self, iri: str, *, except_role: str | None = None) -> Policy: ...
    def label_graph(self, iri: str, level: int) -> Policy: ...
    def fail_closed(self) -> Policy: ...

class QuerySolution:
    @overload
    def __getitem__(self, key: str) -> Any: ...
    @overload
    def __getitem__(self, key: int) -> Any: ...
    def __len__(self) -> int: ...
    @property
    def variables(self) -> list[str]: ...
    def term(self, name: str) -> str | None: ...
    def to_dict(self) -> dict[str, Any]: ...

class Store:
    def __init__(self, path: str | None = None) -> None: ...
    def __len__(self) -> int: ...
    @property
    def dictionary_size(self) -> int: ...
    @property
    def is_persistent(self) -> bool: ...
    def named_graphs(self) -> list[str]: ...
    def load(
        self,
        path: str,
        *,
        format: str | None = None,
        graph: str | None = None,
        bulk: bool = False,
    ) -> int: ...
    def add(
        self,
        subject: str,
        predicate: str,
        object: str | int | float | bool,
        graph: str | None = None,
    ) -> bool: ...
    def query(
        self,
        query: str,
        *,
        principal: Principal | None = None,
        policy: Policy | None = None,
        base_iri: str | None = None,
    ) -> list[QuerySolution] | list[str] | bool: ...
    def update(
        self,
        update: str,
        *,
        principal: Principal | None = None,
        policy: Policy | None = None,
        base_iri: str | None = None,
    ) -> dict[str, int]: ...
    def validate(
        self, shapes: str, *, engine: Literal["native", "vendored"] = "vendored"
    ) -> dict[str, Any]: ...

def has_rocksdb() -> bool: ...
def geosparql_functions() -> list[str]: ...
