#!/usr/bin/env python3
"""Regenerates THIRD-PARTY.md from cargo metadata.

    python scripts/third-party.py > THIRD-PARTY.md

A hand-maintained attribution file is a file that was accurate once. This one is derived
from the actual dependency graph, so a new dependency with an awkward licence shows up the
next time it is run rather than the next time somebody audits by hand.
"""
import collections
import json
import subprocess
import sys

# Licences that would change what this project may be licensed as, or that need a decision.
COPYLEFT = ('GPL', 'AGPL', 'SSPL', 'CC-BY-NC', 'CDDL', 'EPL', 'MPL')


def main():
    if hasattr(sys.stdout, 'reconfigure'):
        sys.stdout.reconfigure(encoding='utf-8')

    # Bytes, then UTF-8: cargo emits UTF-8, and a Windows console's default codec chokes
    # on a non-ASCII author name somewhere in the graph.
    raw = subprocess.run(
        ['cargo', 'metadata', '--format-version', '1'],
        capture_output=True, check=True,
    ).stdout
    meta = json.loads(raw.decode('utf-8'))

    own = {p['name'] for p in meta['packages'] if p['name'].startswith('holos-')}
    third = [p for p in meta['packages'] if p['name'] not in own]

    counts = collections.Counter()
    apache_only = []
    needs_decision = []

    for p in third:
        lic = (p.get('license') or '(none declared)').strip()
        counts[lic] += 1
        upper = lic.upper()
        # A disjunction offering a permissive arm is fine: that arm is the one taken.
        disjunctive = ' OR ' in upper or '/' in lic
        if lic == '(none declared)':
            needs_decision.append((p['name'], lic, 'no licence declared'))
        elif any(c in upper for c in COPYLEFT) and not disjunctive:
            needs_decision.append((p['name'], lic, 'copyleft with no permissive arm'))
        elif lic in ('Apache-2.0', 'Apache-2.0 WITH LLVM-exception'):
            apache_only.append((p['name'], lic, p.get('repository') or ''))

    out = sys.stdout.write
    out('<!-- Generated by `python scripts/third-party.py`. Do not edit; regenerate. -->\n')
    out('# Third-party components\n\n')
    out('Copyright in this project is held by **Peter Winstanley**. This file records what\n')
    out('else is in the tree or linked into it, and under what terms.\n\n')
    out('```sh\npython scripts/third-party.py > THIRD-PARTY.md\n```\n\n')

    out('---\n\n## Code copied into this tree\n\n')
    out('One component. Everything else is a dependency, not a copy.\n\n')
    out('| Component | Origin | Licence | Copyright |\n|---|---|---|---|\n')
    out('| [`holos-shacl-engine`](crates/holos-shacl-engine) | '
        '[pwin/SHACL_Engine](https://github.com/pwin/SHACL_Engine) @ `874e6e57` | '
        'MIT OR Apache-2.0 | Peter Winstanley — **the same holder as this project** |\n\n')
    out('Its `LICENSE-MIT` and `LICENSE-APACHE` are kept in the crate, and\n')
    out('[`PROVENANCE.md`](crates/holos-shacl-engine/PROVENANCE.md) records every change\n')
    out('made to it. Because the upstream copyright holder and this project\'s are the same\n')
    out('person, no third-party copyright attaches to that code.\n\n')

    out('## Approaches reimplemented rather than copied\n\n')
    out('Neither of these contributed any source. A technique is not the thing a licence\n')
    out('covers, and reimplementing one avoids inheriting its terms.\n\n')
    out('| Idea | Origin | Its licence | Why not copied |\n|---|---|---|---|\n')
    out('| CSV → RDF via a TARQL-style `CONSTRUCT` | '
        '[semanticarts/oxi-gen](https://github.com/semanticarts/oxi-gen) | Apache-2.0 **only** | '
        'Copying Apache-only source would force this project to Apache-only, dropping the MIT arm. '
        'See [`holos-tabular`](crates/holos-tabular) |\n')
    out('| Hypertrie / worst-case-optimal joins | '
        '[Tentris](https://dice-research.org/Tentris) | varies | '
        '`DESIGN.md` §12: implement from the papers rather than copy code whose licence is unverified |\n\n')
    out('The `fn:`, `afn:` and `spif:` function libraries are implemented from their\n')
    out('published specifications (W3C XPath F&O, Apache Jena ARQ documentation, SPIN).\n')
    out('Function signatures and semantics are specifications, not source, and the\n')
    out('implementations here were written for this project.\n\n')

    out('---\n\n## Dependency licences\n\n')
    out('%d third-party crates in the full dependency graph.\n\n' % len(third))
    out('| Count | Licence |\n|---:|---|\n')
    for lic, n in counts.most_common():
        out('| %d | %s |\n' % (n, lic))

    out('\n### Requiring anything of us\n\n')
    if needs_decision:
        out('**These need a decision:**\n\n')
        for name, lic, why in sorted(needs_decision):
            out('- `%s` — %s (%s)\n' % (name, lic, why))
    else:
        out('**None.** No copyleft licence without a permissive alternative, and no crate\n')
        out('with an undeclared licence.\n')

    out('\n### Apache-2.0 only\n\n')
    if apache_only:
        out('Depending on these does **not** affect this project\'s licence: linking against\n')
        out('permissively-licensed code imposes nothing on the code that links it. What\n')
        out('Apache-2.0 §4 does ask is that attribution and any `NOTICE` travel with a\n')
        out('**binary distribution**, so a released binary should carry this file.\n\n')
        out('| Crate | Licence | Source |\n|---|---|---|\n')
        for name, lic, repo in sorted(apache_only):
            out('| `%s` | %s | %s |\n' % (name, lic, repo))
    else:
        out('None.\n')

    out('\n---\n\n## Test suites\n\n')
    out('The W3C RDF, SPARQL and SHACL test suites are **fetched, not committed**\n')
    out('(`scripts/fetch-testsuites.sh`) and are excluded by `.gitignore`. They are W3C\n')
    out('material under the W3C Test Suite Licence, and keeping them out of the tree avoids\n')
    out('redistributing third-party fixtures under terms different from this project\'s.\n')


if __name__ == '__main__':
    main()
